// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruddlxrafknsxuqiatdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1ZGRseHJhZmtuc3h1cWlhdGRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDA4MjEsImV4cCI6MjA2NDExNjgyMX0.E_rAUM4hO9R0hqrHctOUctsCiYrwzSA_39zMcGT099c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);